sudo: false

language: node_js
node_js:
  - 8

before_install:
  - npm install coveralls

install:
  - npm install

script:
  - npm run build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
