sudo: false

language: node_js
node_js:
  - 8

cache:
  directories:
    - "node_modules"

before_install:
  - npm install coveralls

install:
  - npm install

script:
  - npm run test && npm run build
  - npm run test:coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
